module load spack/default  gcc/5.4.0 boost
/home/epfl/dforero/scratch/projects/baosystematics/bin/2pcf.py /home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_gal_mock_nowt/DD_files/DD_CATALPTCICz0.638G960S406929492_zspace.radialgauss.sigma0.235.dat /home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_gal_mock_nowt/TwoPCF_CATALPTCICz0.638G960S406929492_zspace.radialgauss.sigma0.235.dat
srun -n 1 -c 16 /home/epfl/dforero/scratch/projects/baosystematics/bin/FCFC_box/2pcf --conf=/home/epfl/dforero/scratch/projects/baosystematics/src/fcfc_box/fcfc_box_void_count_redshift.conf --data=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/mocks_void_xyz_scaledR/CATALPTCICz0.638G960S406929492_zspace.radialgauss.sigma0.235.VOID.dat --count-mode=1 --dd=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_void_mock_nowt_R-loc_scaled1.13-loc_scaled5/DD_files/DD_CATALPTCICz0.638G960S406929492_zspace.radialgauss.sigma0.235.VOID.R-loc_scaled1.13-loc_scaled5.dat --output=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_void_mock_nowt_R-loc_scaled1.13-loc_scaled5/TwoPCF_CATALPTCICz0.638G960S406929492_zspace.radialgauss.sigma0.235.VOID.R-loc_scaled1.13-loc_scaled5.dat --data-wt-col=0 --data-aux-col=5 --data-aux-min=1.13 --data-aux-max=5 --cf-mode=3
module load spack/default  gcc/5.4.0 boost
/home/epfl/dforero/scratch/projects/baosystematics/bin/2pcf.py /home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_gal_mock_nowt/DD_files/DD_CATALPTCICz0.638G960S407794711_zspace.radialgauss.sigma0.235.dat /home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_gal_mock_nowt/TwoPCF_CATALPTCICz0.638G960S407794711_zspace.radialgauss.sigma0.235.dat
srun -n 1 -c 16 /home/epfl/dforero/scratch/projects/baosystematics/bin/FCFC_box/2pcf --conf=/home/epfl/dforero/scratch/projects/baosystematics/src/fcfc_box/fcfc_box_void_count_redshift.conf --data=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/mocks_void_xyz_scaledR/CATALPTCICz0.638G960S407794711_zspace.radialgauss.sigma0.235.VOID.dat --count-mode=1 --dd=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_void_mock_nowt_R-loc_scaled1.13-loc_scaled5/DD_files/DD_CATALPTCICz0.638G960S407794711_zspace.radialgauss.sigma0.235.VOID.R-loc_scaled1.13-loc_scaled5.dat --output=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_void_mock_nowt_R-loc_scaled1.13-loc_scaled5/TwoPCF_CATALPTCICz0.638G960S407794711_zspace.radialgauss.sigma0.235.VOID.R-loc_scaled1.13-loc_scaled5.dat --data-wt-col=0 --data-aux-col=5 --data-aux-min=1.13 --data-aux-max=5 --cf-mode=3
module load spack/default  gcc/5.4.0 boost
/home/epfl/dforero/scratch/projects/baosystematics/bin/2pcf.py /home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_gal_mock_nowt/DD_files/DD_CATALPTCICz0.638G960S408624275_zspace.radialgauss.sigma0.235.dat /home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_gal_mock_nowt/TwoPCF_CATALPTCICz0.638G960S408624275_zspace.radialgauss.sigma0.235.dat
srun -n 1 -c 16 /home/epfl/dforero/scratch/projects/baosystematics/bin/FCFC_box/2pcf --conf=/home/epfl/dforero/scratch/projects/baosystematics/src/fcfc_box/fcfc_box_void_count_redshift.conf --data=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/mocks_void_xyz_scaledR/CATALPTCICz0.638G960S408624275_zspace.radialgauss.sigma0.235.VOID.dat --count-mode=1 --dd=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_void_mock_nowt_R-loc_scaled1.13-loc_scaled5/DD_files/DD_CATALPTCICz0.638G960S408624275_zspace.radialgauss.sigma0.235.VOID.R-loc_scaled1.13-loc_scaled5.dat --output=/home/epfl/dforero/scratch/projects/baosystematics/patchy_results/box5/redshift/radialgauss/tpcf_void_mock_nowt_R-loc_scaled1.13-loc_scaled5/TwoPCF_CATALPTCICz0.638G960S408624275_zspace.radialgauss.sigma0.235.VOID.R-loc_scaled1.13-loc_scaled5.dat --data-wt-col=0 --data-aux-col=5 --data-aux-min=1.13 --data-aux-max=5 --cf-mode=3
